# Use latest ubuntu image
FROM ubuntu:latest
# Update ubuntu packages, then upgrade packages with -y (yes) option
RUN apt-get update && apt-get upgrade -y
# after run send message "Hello, World!"
CMD echo "Hello, World!"
